version: "3"
services:
  middleware:
    build: ./middleware
    volumes:
      - ./middleware:/go/src/github.com/nkjmsss/class_3s_project_enshu/middleware
    environment:
      GO111MODULE: "on"
    tty: true
