version: "2.4"
services:
  middleware:
    build: ./middleware
    volumes:
      - ./middleware:/go/src/github.com/nkjmsss/class_3s_project_enshu/middleware
    ports:
      - 1323:1323
    environment:
      GO111MODULE: "on"
    # network_mode: host
    tty: true
    restart: always
    command: realize start
  controller:
    build: ./controller
    volumes:
      - ./controller:/src
    tty: true
    restart: always
    init: true
    ports:
      - 1324:1324
    command: python server.py
