version: "2"
services:
  middleware:
    build: ./middleware
    volumes:
      - ./middleware:/go/src/github.com/nkjmsss/class_3s_project_enshu/middleware
    environment:
      GO111MODULE: "on"
    tty: true
  controller:
    build: ./controller
    volumes:
      - ./controller:/src
    tty: true
    expose:
      - 1323
