settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: drone
  path: .
  commands:
    build:
      status: true
      method: go build -o /go/bin/drone
    run:
      status: true
      method: /go/bin/drone
    fmt:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
